 # Scipy and Numpy

Scipy builds on Numpy, and for all basic array handling needs you can use Numpy functions:

In [3]:
import numpy as np

If you need to using only some function, you may use the ```from ... import ``` command.

In [4]:
from scipy import some_module
some_module.some_function()

ImportError: cannot import name 'some_module' from 'scipy' (/usr/lib/python3.7/site-packages/scipy/__init__.py)

This whole stuff with numpy is required a lot of practice since it's a big library itself. In this session we only cover some of it. 

## Array


You can make an array right of the blue with ```np.array```.

In [5]:
import numpy as np

a = np.array([[1,2,3],[2,3,4]])
print(a)
print(a[0,1])

[[1 2 3]
 [2 3 4]]
2


As usual, you could access the coordinates with the brackets. Remember that Python start it's counting at 0. For better or worse, Numpy have a different data type than pure Python. We can access the dimension of the matrix with ```a.shape``` if ```a``` is the name of our matriks. It could also reshape with ```a.reshape(m,n)``` where ```(m,n)``` is the new dimension (NumPy can have more than 2 dimensional being). There's also ```arange``` to create an array of evenly spaced numbers. You also could transpose the matrix simply by ```transpose```.

In [8]:
import numpy as np

a = np.array([[1,2,3],[2,3,4]])
b = np.arange(1,7)
c = np.arange(6)
b = b+c
b = b.reshape(2,3)

print(a+b)


[[ 2  5  8]
 [ 9 12 15]]


Numpy has an ability to _broadcast_ matrix, that is to treat arrays of different shapes during arithmetic operations. If the arrays are in the same shape, we did the binary operation coordinat-by-coordinate. But operations on arrays of non-similar shapes is still possible in NumPy. 

In [9]:
a = np.array([1,2,3])
b = np.array([[10,20,30],[20,30,40],[30,40,50]])
a+b

array([[11, 22, 33],
       [21, 32, 43],
       [31, 42, 53]])

## Iteration on Array

You can also iterating in array using ```nditer```. We can compare it if we reshape it first, then iterating as iteration on list, or we iterating directly with nditer. 


In [14]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

print('Transpose of the original array is:')
b = a.T
print(b)
print('\n')

print('Sorted in C-style order:')
c = b.copy(order = 'C')
print(c)
for x in np.nditer(c):
   print(x),

print('\n')

print('Sorted in F-style order:')
c = b.copy(order = 'F')
print(c)
for x in np.nditer(c):
   print(x),

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


## Arithmetic Operations

NumPy is not failed our expectation with linear algebra. Beside binary operation, NumPy also support the "usual" arithmetic operation on matrix, namely: ```np.add```,```np.subtract```,```np.multiply```. 

In [17]:
import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 
b = np.arange(9, dtype = np.float_).reshape(3,3) 
print(a)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
