<a href="https://colab.research.google.com/github/rud72k/workshopintro/blob/master/Matrix%20Helper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Helper

In [ ]:
import numpy as np        # inisiasi numpy untuk membantu perhitungan
invers = np.linalg.inv

In [ ]:
n = 3                             # ukuran 
M = np.array([[1,2,3],            # inisiasi matriks yang akan disolve
             [1,3,4],
             [2,3,5]])
t = np.array([1,2,3])             # inisiasi nilai t awal (vektor)
I = np.identity(n)
print(M)

[[1 2 3]
 [1 3 4]
 [2 3 5]]


In [ ]:
t = np.matmul(invers(I-M),t)      # mengupdate nilai t

[-0.3872  2.0272 -1.1888]
